### ISSUE TITLE
Booking.jsx is trying to import itself

### ISSUE THREAD

**Issue by Harshit-Saxena** [Pulkit-s21/Bhaargav-FInco#2]
> src/components/Booking.jsx (2:9): 

"Booking" is not exported by "src/components/Booking.jsx", imported by "src/components/Booking.jsx".

![Screenshot 2024-08-02 at 11 08 30 PM](https://github.com/user-attachments/assets/2d891e61-81ea-4707-abe4-9e51299e8c84)

**Comment by Pulkit-s21** [comment]
fixed and resolved. Deployed on Netlify.app --> https://66ad256f660d400008633c28--bhaargav.netlify.app/
